site:
  title: bytefield-svg
  url: https://bytefield-svg.deepsymmetry.org
  start_page: bytefield-svg::intro.adoc
content:
  sources:
  - url: https://github.com/Deep-Symmetry/bytefield-svg.git
    branches: [master]
    start_path: doc
asciidoc:
  extensions:
  - asciidoctor-mathjax
plugins:
  - path: antora-generic-svg-extension-plugin
    config:
      generator: bytefield-svg
      name: bytefield
  - path: antora-lunr
ui:
  bundle:
    url: https://deepsymmetry.org/media/antora/ui-bundle.zip
    snapshot: true
